# configs/rewards.yaml
# Reward weights for CLARA analog layout training
# Must match the RewardCalculator implementation

# Base reward weights (used by RewardCalculator)
# base_weights:
#   # Core objectives  
#   completion: 1.0           # Reward for placing all components
#   symmetry: 0.2            # Reward for symmetric placement of matched pairs
#   compactness: 0.45        # Reward for compact bounding box layouts
#   connectivity: 0.0        # Reward for minimizing connection distances
#   device_grouping: 0.0     # NEW: Reward for grouping same device models together
  
#   # Step rewards/penalties
#   placement_step: 0.1      # Small reward per successful placement
  
#   # Violation penalties
#   invalid_action: -100.0     # Penalty for invalid actions
#   # configs/rewards.yaml
# # Reward weights for CLARA analog layout training
# # Must match the RewardCalculator implementation

# Base reward weights (used by RewardCalculator)
base_weights:
  # Positive rewards
  completion: 10.0          # Reward for placing all components
  symmetry: 2.0            # Reward for symmetric placement of matched pairs
  compactness: 1.0         # Reward for compact bounding box layouts
  connectivity: 1.0        # Reward for minimizing connection distances
  device_grouping: 1.0     # Reward for grouping same device models together
  placement_step: 0.5      # Small reward per successful placement
  
  # Graduated penalties (replace binary invalid_action/invalid_placement)
  overlap_severity: -25.0   # Per unit overlap area
  bounds_violation: -15.0   # Per unit out of bounds
  spacing_violation: -10.0  # Per unit spacing violation
  
  # Learning signals
  near_miss_bonus: 3.0     # For almost-valid attempts

# # Adaptive weights for curriculum learning (used by AdaptiveRewardCalculator)
# curriculum_weights:
#   early_training:          # Progress < 0.3
#     placement_step: 2.0
#     symmetry: 0.5
#     compactness: 2.0
#     connectivity: 0.5
    
    
#   mid_training:           # 0.3 <= progress < 0.7
#     placement_step: 1.0
#     symmetry: 1.5
#     compactness: 1.5
#     connectivity: 1.0
    
    
#   late_training:          # Progress >= 0.7
#     placement_step: 0.5
#     symmetry: 3.0
#     compactness: 1.0
#     connectivity: 2.0
    

# # Configuration for curriculum learning
# curriculum_config:
#   full_curriculum_episodes: 1000  # Episodes to complete full curriculum